filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata:
          in_cluster: true

    output.elasticsearch:
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
      protocol: https
      hosts: ["security-master:9200"]
      ssl.certificate_authorities: 
        - /usr/share/filebeat/config/certs/elastic-certificate.pem
      ssl.certificate: /usr/share/filebeat/config/certs/elastic-certificate.pem
      ssl.key: /usr/share/filebeat/config/certs/filebeat/elastic-certificates.p12

secretMounts:
  - name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /usr/share/filebeat/config/certs
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/filebeat/config/certs/filebeat

extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
